### ISSUE TITLE
Theseus dead?

### ISSUE THREAD

**Issue by nmaxcom** [adobe-research/theseus#87]
I'd like to know if this tool is being maintained or not.

It's still featured in the Brackets GitHub but seems dead with plenty of unresolved issues and 4-year-old code.

**Comment by alltom** [comment]
I periodically hear about Theseus's constituent libraries (fondue, etc) being used in other projects, but I haven't had the chance to bring the interface up to date with Brackets' recent releases. I'd help anyone who wants to send pull requests, though.
